name: Will Roe's keymaps
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install gcc unzip wget zip gcc-avr binutils-avr avr-libc dfu-programmer dfu-util gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi
      - name: Download submodules
        run: |
          make git-submodule
      - name: Build firmware
        run: make crkbd:will_plancklike
      - name: Upload firmware
        uses: actions/upload-artifact@main
        with:
          name: crkbd_rev1_will_plancklike.hex
          path: crkbd_rev1_will_plancklike.hex
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload release asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: crkbd_rev1_will_plancklike.hex
          asset_name: crkbd_rev1_will_plancklike.hex
